### ISSUE TITLE
[v4]: Is it possible to set filename [name].[ext] instead of [hash][ext]

### ISSUE THREAD

**Issue by rkovalov** [bholloway/resolve-url-loader#213]
Before I used v3 with `file-loader` for resolving paths and naming,
But with webpack v5 this tandem doest work

```js
{
        test: /\.(woff|eot|ttf|woff2|otf)$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "./fonts/[name].[ext]",
              // esModule must be false for properly resolve url by resolve-url-loader
              esModule: false,
            },
          },
        ],
 }
 ```

**Comment by bholloway** [comment]
Here we are dealing only with the asset source files. The final emitted files has nothing to do with `resolve-url-loader`.

However I think you are on the right track looking at `file-loader`.

I am closing for now since I cannot help further. Feel free to comment further. I will reopen as necessary.
