### ISSUE TITLE
incompatible with sass-loader 3.2.2 

### ISSUE THREAD

**Issue by e-cloud** [bholloway/resolve-url-loader#22]
As sass-loader fix something about it's sourcemap, resolve-url-loader can not find the correct resource and crash.

**Comment by larrydahooster** [comment]
It does not crash for me but I am getting this warnings since update from sass-loader 3.2.1 -> 3.2.2 and resolve-url-loader 1.4.3 -> 1.4.4 :

WARNING in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/resolve-url-loader!./~/sass-loader?sourceMap!./src/stylesheets/selectorButton.scss

resolve-url-loader cannot operate: source-map error
cannot establish a common base path for all sources in the incoming source-map

**Comment by rewop** [comment]
I have the same problem. It looks like the issue is [a bug in sass-loader@3.2.2](https://github.com/jtangelder/sass-loader/pull/250).
