### ISSUE TITLE
Not working when url start with `/`

### ISSUE THREAD

**Issue by idangozlan** [bholloway/resolve-url-loader#48]
Hi,

Maybe I'm doing something wrong, when im using the following syntax:
`background: url(/myimage.png);`
is not working, but when im using:
`background: url(myimage.png)`
It's working.

Any solution?

**Comment by bholloway** [comment]
You are specifying a file. Similar to js imports in node.

So no slash or dot-slash is relative to the CSS or SCSS file. Whereas a
leading slash is an absolute path.

It would be interesting to use the new debug option and see what paths are
being searched in that case. I think it would fail immediately since the
path is outside the project.

If you want to access a package then use a leading tilde "~" and then
package name. Otherwise use relative paths.

**Comment by idangozlan** [comment]
Thank you!
