### ISSUE TITLE
Size of bundle increased when migrating to version 2

### ISSUE THREAD

**Issue by baywet** [bholloway/resolve-url-loader#49]
Hi,
I recently migrated a few projects resolve-url-loader from 1.6.1 to 2.0.2.
Doing so they all gained 800k before minification, no matter the size of the project or the number of assets.
Is there anything new I should know about in terms of configuration introduce by v2?
Thanks!

**Comment by bholloway** [comment]
Wow that's crazy. Doesn't make any sense.

Can you provide a small reference project open source?

**Comment by bholloway** [comment]
A thought: Maybe sourceMap sources are included and were not before.

**Comment by baywet** [comment]
I can maybe provide a cleaned project if needed. Just to give more context about this issue. I'm using webpack 2, and not directly resolve-url-loader but via bootstrap-loader. I feel there's something like the default behavior for version 1.X of resolve-url-loader was no source map and now there's with v2. Still investigating

**Comment by bholloway** [comment]
@baywet I have taken a look over the code changes between these versions and I cannot think of how this could occur. Are you sure there are no other aspects of your Webpack build that have changed?

I think that you would need to provide me with a simple project where simply installing a different version of `resolve-url-loader` (and making no other changes) exhibits this problem.

That may seem onerous but I can't see any other path to isolating the cause of this issue.

**Comment by baywet** [comment]
Here you go https://github.com/baywet/resolve-url-loader-size-iusse
```
npm install
npm run build:prod => the dummy-elektron.js is about 700k
npm i resolve-url-loader@latest -D
npm run build:prod => same file is about 1.4MB
```
Thanks for your help

**Comment by bholloway** [comment]
### Some pictures

Using [webpack bundle visualizer](https://chrisbateman.github.io/webpack-visualizer/)

Most of your bundle is `noop`, from the `bootstrap-loader`.

With older loader

![image](https://cloud.githubusercontent.com/assets/6868309/24130509/12b1a95e-0e3d-11e7-90b5-a49980f540bd.png)

With newer loader

![image](https://cloud.githubusercontent.com/assets/6868309/24130495/fa11b268-0e3c-11e7-95d7-016090a486d7.png)

### Some dirty debugging

In the `resolve-url-loader/index.js:126` I put 
```
console.log(JSON.stringify(reworked.map, null, 2));
```

That gave me the content of the source-map going out.

In both cases there are source-map `sourcesContent` in the CSS output map. In the first case it doesn't seem to include any `import`ed `scss` files, only the top level bootstrap file. But in the later case this has been fixed and it is **much larger**.

This is possibly due to a bump in the source-map generator dependency: [from this](https://github.com/bholloway/resolve-url-loader/blob/1.6.1/package.json#L36) => [to this](https://github.com/bholloway/resolve-url-loader/blob/2.0.2/package.json#L36). I have not gone further with this.

### Thats not the point!

For production you are extracting your source-map. **GOOD**

However because you aren't extracting your CSS, you have not extracted your CSS source-map. **BAD**

Personally I don't believe in `sourcesContent`. I think you need to be able to debug back to your original source-code. But that is a beside the point.

I would suggest extracting you CSS anyway. It will improve your load time and prevent "flash of unstyled content" problems.

### Anything to fix?

**For `resolve-url-loader`: (methinks) no.**

Please confirm my working but I think the issue is that the source-maps are **more correct** than they used to be.

**For @baywet: yes.**

You need to be in a position where the "correctness" of the source-maps does not impact your production build.

**Comment by baywet** [comment]
Thanks for the very detailed investigation on the subject.
In my case updating `.bootstraprc` file to the following configuration forced it to output the bootstrap css and css map to my extracted css and to a dedicated css sourcemap file.
The size of the main javascript bundle decreased to 180KB, sourmaps and css sizes augmented as predicted even after upgrading to latest version of resolve-url-loader
```
env:
  Development:
    extractStyles: false
  Production:
    extractStyles: true
```

**Comment by bholloway** [comment]
No problem @baywet, happy to help. Glad you got a result.
