### ISSUE TITLE
Works in debug but not in production

### ISSUE THREAD

**Issue by AaronLayton** [bholloway/resolve-url-loader#84]
I am having with getting this to run in production

```
{
    test: /\.scss$/,
    use:  ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
            {
                loader: 'css-loader',
                options: {
                    sourceMap: true,
                    url: true
                }
            },
            "resolve-url-loader",
            "sass-loader?sourceMap"
        ]
    })
}
```

My folder structure is as below

`/content/css/main.scss`
`/content/css/bem/myfile.scss`
`/content/img/download.svg`

`myfile` references an svg with `background-image: url('../../img/downloaded.svg');`

the `resolve-url-loader` correctly fixes the reference when using the straight `webpack` command but if I use `webpack -p` it can no longer find the correct file

**Comment by Spetnik** [comment]
Same here. Using webpack 3.11.0. `webpack -d` works fine. `webpack -p` produces tons of `Module not found: Error: Can't resolve...` messages

**Comment by Spetnik** [comment]
Update: it seems that by moving the lines that reference the urls to a point later in the file, the issue is resolved. Build still takes forever though...

**Comment by ganyusheng520** [comment]
the same in webpack 3.10.0

**Comment by bholloway** [comment]
@AaronLayton covered this in e2e tests but can't reproduce. Could you please submit a small example project that we can look at in detail.

**Comment by cholnhial** [comment]
@Spetnik You were right moving the troublesome stylesheets around fixes the issue. I moved the stylesheets that were causing the error all the way down in the file.

**Comment by bholloway** [comment]
So historically `-p` has been a shortcut for some other options. See [webpack 3](https://github.com/webpack/webpack/blob/v3.10.0/bin/config-yargs.js#L270) as an example (since webpack 3 was mentioned).

If I recall correctly there was a problem with certain versions of `sass-loader` when minimising the output css. That said I am using `node-sass@^4` in the e2e tests and I do not have to do anything special to make that work.

Can ppl pls state their `node-sass` version, if only to eliminate that angle.

**Comment by bholloway** [comment]
I am linking #32 in case it is relevant.

**Comment by cholnhial** [comment]
@bholloway my `node-sass` version is `4.5.3`.

**Comment by bholloway** [comment]
Please refer to #97 as version 3 may help any open issues.

**Comment by bholloway** [comment]
I'm going to close this ageing issue because we have a new version `3.0.0` which (e2e testing confirms) is much better.

Please open a fresh issue for any ongoing problems and link to this one as needed.

I'm not opposed to reopening this issue but certainly lets talk with respect to the new version.

**Comment by donnysim** [comment]
For anyone still having this problem (also with v3 and webpack 4), I've found it that it occurs with libass, moving to node-sass implementation solved the problem for me.

```js
{
  loader: 'resolve-url-loader',
},
{
  loader: 'sass-loader',
  options: {
    sourceMap: true,
    implementation: require('sass'),
  },
},
```

though you might have to fix other problems as node-sass is updated while libass is stale and ignores most of the errors and misses new features like `@use`.

Can't reproduce this issue in a clean project to provide a demo and was unable to find the problem while debugging.
